server:
  port: ${SERVER_PORT:8080}
  servlet:
    encoding:
      charset: 'UTF-8'
      enabled: true
      force: true
    context-path: '/'

spring:
  mvc:
    view:
      prefix: '/WEB-INF/jsp/'
      suffix: '.jsp'
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'
    database: postgresql
    show-sql: false
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://${DB_URL:localhost}:${DB_PORT:5432}/${DB_NAME:portfolio}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  sql:
    init:
      mode: always

paging:
  page:
    number: 1
    size: 10


